sudo: required

services:
  - docker

jobs:
  include:
    - stage: Pull
      script: docker pull p13i/csp
    
    - stage: Test
      script: docker run -v $(pwd):/csp -w /csp p13i/csp bash csp test
    
    - stage: State
      script:
        - docker --version
        - docker images
        - docker ps
