#!/usr/bin/env bash

set -e

# Prints usage for this command line tool
function csp_usage() {
cat<<- EOF

${bold}Constraint Satisfaction Problems${normal}

${bold}SETUP${normal}

    chmod +x csp
    alias csp="./csp"
    
${bold}USAGE${normal}

    csp [COMMAND]

${bold}COMMANDS${normal}

    (blank)     Print this help dialogue
    build       Build the program
    test        Run the tests

${bold}VERSION${normal}

    0.0.0


${bold}DEVELOPER${normal}

    Pramod Kotipalli -- https://github.com/p13i

EOF
}

# Configures the shell with colors if it supports it
# Based on: https://unix.stackexchange.com/a/10065
function config_shell {
    if test -t 1; then
        ncolors=$(tput colors)
        if test -n "$ncolors" && test $ncolors -ge 8; then
            bold="$(tput bold)"
            normal="$(tput sgr0)"
            red="$(tput setaf 1)"
            green="$(tput setaf 2)"
            yellow="$(tput setaf 3)"
        fi
    fi
}

# Runs the build functionality
function csp_build() {
    echo "${bold}${yellow}Building...${normal}"
    mkdir -p Build/
    mcs -out:Build/Tests.exe Tests/*.cs Source/*.cs
    echo "${bold}${green}Done.${normal}"
}

# Runs the test functionality
function csp_test() {
    echo "${bold}${yellow}Testing...${normal}"
    mono Build/Tests.exe
    echo "${bold}${green}Done.${normal}"
}

# Configure this shell
config_shell

# If there are no arguments, then display the usage
if [[ $# == 0 ]]; then
    csp_usage
    exit 1

# If there is one argument, then find out if it was a build or test command
elif [[ $# == 1 ]]; then

    if [[ "$1" == "build" ]]; then
        # Run only the build step
        csp_build
        exit 0
    elif [[ "$1" == "test" ]]; then
        # Run both the build and test steps
        csp_build
        csp_test
        exit 0
    fi

fi

echo "${red}Error${normal}: Unknown command: ${@}"
